<?php
namespace SMA\PAA;

function routes()
{
    $server = new Server();
    return array_merge([
        "POST:/login"                                 => "login:Auth:login"
        ,"POST:/logout"                               => "login:Auth:logout"
        ,"GET:/session"                               => "login:Auth:session"
        ,"POST:/register-push-token"                  => "basic_user_action:User:registerPushToken"
        ,"GET:/users"                                 => "manage_user:User:list"
        // Further permission checking done in user service
        ,"POST:/users"                                => "manage_user:User:add"
        // Further permission checking done in user service
        ,"PUT:/users/:id"                             => "manage_user:User:update"
        ,"GET:/users/:id"                             => "manage_user:User:get"
        // Further permission checking done in user service
        ,"DELETE:/users/:id"                          => "manage_user:User:delete"
        ,"POST:/user-suspend"                         => "manage_user:User:setUserSuspend"
        ,"POST:/user-lock"                            => "manage_user:User:setUserLock"
        ,"POST:/register"                             => "public:User:register"
        ,"POST:/codeless-register"                    => "public:User:codelessRegister"
        ,"POST:/request-password-reset"               => "public:Auth:requestPasswordReset"
        ,"POST:/reset-password"                       => "public:Auth:resetPassword"
        ,"POST:/change-password"                      => "manage_user:Auth:changePassword"
        ,"POST:/timestamps"                           => "add_manual_timestamp:Agent:timestamp"
        ,"GET:/timestamp-definitions"                 => "add_manual_timestamp:Timestamp:getTimestampDefinitions"

        // Note: this url might be later replaced with another container via proxy
        // Don't touch these - given to customers already and/or used by agents
        // ****************************************************************************
        ,"POST:/agent/rest/timestamps"                => "timestamp:Agent:timestamp"
        ,"POST:/agent/rest/logistics-timestamps"      => "timestamp:Agent:logisticsTimestamp"
        ,"POST:/agent/rest/vis-notifications"         => "timestamp:Agent:visNotifications"
        ,"POST:/agent/rest/vis-messages"              => "timestamp:Agent:visMessages"
        ,"POST:/agent/rest/vis-voyage-plans"          => "timestamp:Agent:visVoyagePlans"
        ,"POST:/agent/rest/vis-vessels"               => "timestamp:Agent:visVessels"
        ,"POST:/agent/rest/live-eta"                  => "timestamp:Agent:liveEta"
        ,"POST:/agent/rest/inbound-vessels"           => "timestamp:Agent:inboundVessel"
        ,"POST:/agent/rest/slot-reservations"         => "timestamp:Agent:addSlotReservation"
        ,"PUT:/agent/rest/slot-reservations"          => "timestamp:Agent:updateSlotReservation"
        ,"GET:/agent/rest/slot-reservation-by-id"     => "timestamp:Agent:getSlotReservationById"
        ,"DELETE:/agent/rest/slot-reservations"       => "timestamp:Agent:cancelSlotReservation"
        // ****************************************************************************

        ,"GET:/port-calls"                            => "basic_user_action:PortCall:list"
        ,"GET:/port-call-timestamps"                  => "basic_user_action:PortCall:timestamps"
        ,"GET:/non-port-call-timestamps"              => "basic_user_action:PortCall:timestampsWithoutPortCall"
        ,"GET:/ongoing-port-calls"                    => "basic_user_action:PortCall:portCallsOngoing"
        ,"GET:/port-call"                             => "basic_user_action:PortCall:portCallTimelineObject"
        ,"GET:/port-call-csv"                         => "basic_user_action:PortCall:portCallTimelineObjectCsv"
        ,"GET:/port-call-template"                    => "basic_user_action:PortCallTemplate:get"
        ,"GET:/logistics-timestamps/:limit"           => "basic_user_action:Logistics:filtered"
        ,"GET:/logistics-timestamps/by-license-plate/:license_plate"
                                                      => "basic_user_action:Logistics:one"
        ,"POST:/rta-web-form"                         => "send_rta_web_form:ClientRtaWebForm:rtaWebForm"
        ,"GET:/api-keys"                              => "manage_api_key:ApiKey:list"
        ,"POST:/api-keys"                             => "manage_api_key:ApiKey:create"
        ,"PUT:/api-keys/disable"                      => "manage_api_key:ApiKey:disable"
        ,"PUT:/api-keys/enable"                       => "manage_api_key:ApiKey:enable"
        ,"GET:/health-check"                          => "public:Diagnostics:healtCheck"
        // ,"GET:/phpinfo"                               => "public:Diagnostics:phpinfo"
        ,"POST:/translation/:ns/:lng"                 => "translation:Translation:add"
        ,"GET:/translations/:ns/:lng"                 => "public:Translation:get"
        ,"PUT:/translations/:ns/:lng"                 => "manage_translation:Translation:update"
        ,"POST:/translations/:ns/:lng"                => "manage_translation:Translation:upload"
        ,"GET:/registration-codes/:limit"             => "manage_registration_code:RegistrationCodes:list"
        ,"POST:/registration-codes"                   => "manage_registration_code:RegistrationCodes:add"
        ,"PUT:/registration-codes/:id"                => "manage_registration_code:RegistrationCodes:update"
        ,"DELETE:/registration-codes/:id"             => "manage_registration_code:RegistrationCodes:delete"
        ,"GET:/notifications/:limit"                  => "basic_user_action:Notification:list"
        ,"POST:/notifications"                        => "send_push_notification:Notification:add"
        ,"DELETE:/notifications/:id"                  => "delete_push_notification:Notification:delete"
        ,"GET:/pinned-vessel-ids"                     => "basic_user_action:PinnedVessel:getVesselIds"
        ,"PUT:/pinned-vessel-ids"                     => "basic_user_action:PinnedVessel:setVesselIds"
        ,"GET:/settings"                              => "basic_user_action:Setting:getAll"
        ,"GET:/settings/by-name/:name"                => "basic_user_action:Setting:getByName"
        ,"PUT:/settings/:name/:value"                 => "manage_setting:Setting:update"
        ,"GET:/public-settings"                       => "public:Setting:getPublicSettingByName"
        ,"GET:/roles"                                 => "basic_user_action:Role:get"
        ,"GET:/permissions"                           => "basic_user_action:Permission:get"
        ,"GET:/role-permissions"                      => "basic_user_action:RolePermission:getAll"
        ,"GET:/role-permissions/by-role/:role"        => "basic_user_action:RolePermission:getByRole"
        ,"PUT:/role-permissions/:role/:permission"    => "manage_permission:RolePermission:add"
        ,"DELETE:/role-permissions/:role/:permission" => "manage_permission:RolePermission:delete"
        ,"POST:/push-notification-tokens"             => "push_notification_token:PushNotification:removeStaleTokens"
        ,"GET:/export/timestamps"                     => "export_api:Export:timestamps"
        ,"GET:/timestamps"                            => "manage_port_call:Export:timestamps"
        ,"DELETE:/timestamps"                         => "manage_port_call:Timestamp:delete"
        ,"GET:/export/port-calls"                     => "export_api:Export:portCalls"
        ,"GET:/vessels"                               => "basic_user_action:Vessel:list"
        ,"POST:/vessel-visibility"                    => "manage_port_call:Vessel:setVesselVisibility"
        ,"GET:/vis-services"                          => "view_vis_information:Vis:getService"
        ,"GET:/vis-vessels"                           => "view_vis_information:Vis:getVessel"
        ,"GET:/vis-voyage-plans"                      => "view_vis_information:Vis:getVoyagePlan"
        ,"GET:/vis-text-messages"                     => "view_vis_information:Vis:getTextMessage"
        ,"GET:/vis-notifications"                     => "view_vis_information:Vis:getNotification"
        ,"POST:/vis-text-messages-with-imo"           => "send_vis_text_message:Vis:sendTextMessageWithImo"
        ,"POST:/vis-text-messages"                    => "send_vis_text_message:Vis:sendTextMessage"
        ,"POST:/vis-send-rta"                         => "send_vis_rta:Vis:sendRta"
        ,"GET:/vis-service-poll"                      => "view_vis_information:Vis:pollVisService"
        ,"GET:/vis-configuration"                     => "view_vis_information:Vis:getVisServiceConfiguration"
        ,"POST:/update-port-call-id"                  => "manage_port_call:Timestamp:updatePortCallId"
        ,"POST:/unset-port-call-id"                   => "manage_port_call:Timestamp:unsetPortCallId"
        ,"POST:/restore-timestamp"                    => "manage_port_call:Timestamp:untrashById"
        ,"GET:/rebuild-port-calls"                    => "manage_port_call:PortCall:rebuildPortCalls"
        ,"GET:/timestamps-to-port-calls"              => "manage_port_call:PortCall:timestampsToPortCalls"
        ,"GET:/force-close-port-call"                 => "manage_port_call:PortCall:forceClosePortCall"
        ,"GET:/force-scan-port-call"                  => "manage_port_call:PortCall:forceScanPortCall"
        ,"GET:/port-call-range"                       => "manage_port_call:PortCall:getPortCallRange"
        ,"POST:/port-call-range"                      => "manage_port_call:PortCall:setPortCallRange"
        ,"GET:/inbound-vessels"                       => "basic_user_action:InboundVessel:list"
        ,"POST:/ports"                                => "manage_port:Port:add"
        ,"GET:/ports"                                 => "manage_port:Port:list"
        ,"POST:/port-whitelist-in"                    => "manage_port:Port:setWhiteListIn"
        ,"POST:/port-whitelist-out"                   => "manage_port:Port:setWhiteListOut"
        ,"POST:/berths"                               => "manage_berth:Berth:add"
        ,"PUT:/berths"                                => "manage_berth:Berth:update"
        ,"DELETE:/berths"                             => "manage_berth:Berth:delete"
        ,"GET:/berths"                                => "view_berth:Berth:list"
        ,"GET:/berth-by-id"                           => "view_berth:Berth:get"
        ,"POST:/own-nominations"                      => "manage_own_queue_nomination:Nomination:ownAdd"
        ,"PUT:/own-nominations"                       => "manage_own_queue_nomination:Nomination:ownUpdate"
        ,"DELETE:/own-nominations"                    => "manage_own_queue_nomination:Nomination:ownDelete"
        ,"GET:/own-nominations"                       => "view_own_queue_nomination:Nomination:ownList"
        ,"GET:/own-nomination-by-id"                  => "view_own_queue_nomination:Nomination:ownGet"
        ,"GET:/all-nominatable-berths"                => "view_own_queue_nomination:Nomination:getAllNominatableBerths"
        ,"GET:/consignee-users"                       => "view_all_queue_nomination:Nomination:getConsigneeUsers"
        ,"POST:/nomination-for-consignee"             => "manage_all_queue_nomination:Nomination:addForConsignee"
        ,"PUT:/nominations"                           => "manage_all_queue_nomination:Nomination:update"
        ,"DELETE:/nominations"                        => "manage_all_queue_nomination:Nomination:delete"
        ,"GET:/nominations"                           => "view_all_queue_nomination:Nomination:list"
        ,"GET:/nomination-by-id"                      => "view_all_queue_nomination:Nomination:get"
        ,"POST:/berth-reservations"                   => "manage_berth_reservation:BerthReservation:add"
        ,"PUT:/berth-reservations"                    => "manage_berth_reservation:BerthReservation:update"
        ,"DELETE:/berth-reservations"                 => "manage_berth_reservation:BerthReservation:delete"
        ,"GET:/berth-reservations"                    => "view_berth_reservation:BerthReservation:list"
        ,"GET:/berth-reservation-by-id"               => "view_berth_reservation:BerthReservation:get"
        ,"POST:/slot-reservations"                    => "manage_queue_slot_reservation:SlotReservation:add"
        ,"PUT:/slot-reservations"                     => "manage_queue_slot_reservation:SlotReservation:update"
        ,"DELETE:/slot-reservations"                  => "manage_queue_slot_reservation:SlotReservation:delete"
        ,"GET:/slot-reservations"                     => "view_queue_slot_reservation:SlotReservation:list"
        ,"GET:/slot-reservation-by-id"                => "view_queue_slot_reservation:SlotReservation:get"
        ,"GET:/dashboard-slot-reservations"           => "view_queue_slot_reservation:SlotReservation:dashboardList"
        ,"GET:/timestamp-api-key-weights"             => "manage_api_key:TimestampApiKeyWeight:list"
        ,"POST:/timestamp-api-key-weights"            => "manage_api_key:TimestampApiKeyWeight:modify"
        ,"GET:/sea-chart/vessels"                     => "basic_user_action:SeaChart:vessels"
        ,"GET:/sea-chart/markers"                     => "basic_user_action:SeaChart:markers"
        ,"POST:/sea-chart/vessels"                    => "update_sea_chart_location:SeaChart:updateVesselLocations"
        ,"GET:/sea-chart/fixed-vessels"               => "manage_sea_chart_vessel:SeaChart:fixedVessels"
        ,"POST:/sea-chart/fixed-vessel"               => "manage_sea_chart_vessel:SeaChart:addFixedVessel"
        ,"DELETE:/sea-chart/fixed-vessel"             => "manage_sea_chart_vessel:SeaChart:deleteFixedVessel"
        ,"GET:/payload-key-api-key-weights"           => "manage_api_key:PayloadKeyApiKeyWeight:list"
        ,"POST:/payload-key-api-key-weights"          => "manage_api_key:PayloadKeyApiKeyWeight:modify"
        ,"GET:/sea-chart/fixed-vessel"                => "manage_sea_chart_vessel:SeaChart:fixedVessel"
        ,"PUT:/sea-chart/fixed-vessel"                => "manage_sea_chart_vessel:SeaChart:updateFixedVessel"
        ,"GET:/decisions"                             => "basic_user_action:Decision:list"
        ,"GET:/decision-by-id"                        => "basic_user_action:Decision:get"
        ,"POST:/close-decision"                       => "send_push_notification:Decision:close"
        ,"DELETE:/decisions"                          => "delete_push_notification:Decision:delete"
        ,"POST:/decision-item-response"               => "send_push_notification:Decision:setDecisionItemResponse"
        ,"GET:/vessel-types"                          => "basic_user_action:Vessel:vesselTypes"
        ,"PUT:/vessel"                                => "manage_vessel:Vessel:updateVessel"
    ], $server->isDev() ? [
    ] : []);
}
