image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        caches:
          - composer
          - docker
        script:
          - apk add --no-cache make
          - make ci

