version: '3.7'


services:
  postgres:
    image: postgres:alpine
    volumes:
      - spia-postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5532:5432"
    container_name: spia-dev
    env_file: .env

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    container_name: spia-redis

  api:
    image: nginx:alpine
    stop_signal: SIGINT
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code:rw,consistent
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,consistent
    ports:
      - "${EXPOSED_API_PORT}:80"
    links:
      - php
    container_name: spia-api

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code:rw,consistent
    container_name: spia-php

  socket:
    build:
      context: socket
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_SOCKET_PORT}:8000"
    volumes:
      - .:/code:rw,consistent
    container_name: spia-socket
    env_file: .env

  push-notifications:
    build:
      context: push-notifications
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_PUSH_NOTIFICATIONS_PORT}:8000"
    volumes:
      - ./push-notifications:/usr/src/:rw,consistent
    container_name: spia-push-notifications
    env_file: .env
    command: ["npm", "run", "start:watch"]

volumes:
  spia-postgres:
  src:
  database:
  vendor:
