version: '3.7'


services:
  postgres:
    image: postgres:alpine
    container_name: spia-postgres-integration
    env_file: ../.env

  redis:
    image: redis:alpine
    container_name: spia-redis-integration

  api:
    build:
      context: ..
      dockerfile: Dockerfile
    stop_signal: SIGINT
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/code:rw,consistent
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,consistent
    ports:
      - "8001:80"
    links:
      - php
    container_name: spia-api-integration

  php:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/code:rw,consistent
