version: '3.7'


services:
  postgres:
    image: postgres:alpine
    container_name: spia-postgres-integration

  redis:
    image: redis:alpine
    container_name: spia-redis-integration

  api:
    image: nginx:alpine
    stop_signal: SIGINT
    depends_on:
      - postgres
      - redis
    volumes:
      - ..:/code:rw,consistent
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:rw,consistent
    links:
      - php
    container_name: spia-api-integration

  php:
    env_file:
      - features.env
    environment:
      - SKIP_LOCAL_INIT=1
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/code:rw,consistent
    container_name: spia-integration-php
